### ISSUE TITLE
Unable to bootstrap, error when npm run dev

### ISSUE THREAD

**Issue by athom** [fundon/vue-admin#32]
➜  vue-admin git:(master) cnpm --version
4.2.0
➜  vue-admin git:(master) node --version
v6.2.1

```
 vue-admin git:(master) cnpm run dev

> vue-admin@0.0.1 dev /Users/yeer/go/src/github.com/fundon/vue-admin
> node build/dev-server.js

Listening at http://localhost:8080

webpack built 40e0165a1044ed4c4d47 in 17772ms
Hash: 40e0165a1044ed4c4d47
Version: webpack 1.13.1
Time: 17772ms
                                           Asset     Size  Chunks       Chunk Names
  static/fonts/MaterialIcons-Regular.a37b0c0.ttf   128 kB
    static/fonts/fontawesome-webfont.25a3241.eot  76.5 kB
  static/fonts/fontawesome-webfont.e6cf7c6.woff2  71.9 kB
   static/fonts/fontawesome-webfont.c8ddf1e.woff  90.4 kB
      static/img/fontawesome-webfont.d7c6390.svg   392 kB
  static/fonts/MaterialIcons-Regular.e79bfd8.eot   143 kB
    static/fonts/fontawesome-webfont.1dc35d2.ttf   153 kB
 static/fonts/MaterialIcons-Regular.012cf6a.woff  57.6 kB
static/fonts/MaterialIcons-Regular.570eb83.woff2  44.3 kB
                     static/img/logo.5c8c1f0.png    11 kB
                  static/img/logo@2x.108f7a8.png  24.1 kB
                                          0.0.js  13.5 MB       0
                                          app.js  3.25 MB       1       app

ERROR in ./~/.npminstall/vue-bulma-jump/0.0.0/vue-bulma-jump/src/index.js
Module parse failed: /Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/vue-bulma-jump/0.0.0/vue-bulma-jump/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:7)
    at Parser.pp.raise (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1490:8)
    at Parser.pp.expect (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1484:26)
    at Parser.pp.parseExportSpecifiers (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:2229:8)
    at Parser.pp.parseExport (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:2201:28)
    at Parser.pp.parseStatement (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1762:85)
    at Parser.pp.parseTopLevel (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1666:21)
    at Parser.parse (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1632:17)
    at Object.parse (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack/1.13.1/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack/1.13.1/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/enhanced-resolve/0.9.1/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/graceful-fs/4.1.4/graceful-fs/graceful-fs.js:78:16
 @ ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/Components/BackToTop.vue 7:20-45

ERROR in ./~/.npminstall/vue-bulma-progress-tracker/0.0.1/vue-bulma-progress-tracker/src/index.js
Module parse failed: /Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/vue-bulma-progress-tracker/0.0.1/vue-bulma-progress-tracker/src/index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:7)
    at Parser.pp.raise (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1490:8)
    at Parser.pp.expect (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1484:26)
    at Parser.pp.parseExportSpecifiers (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:2229:8)
    at Parser.pp.parseExport (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:2201:28)
    at Parser.pp.parseStatement (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1762:85)
    at Parser.pp.parseTopLevel (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1666:21)
    at Parser.parse (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:1632:17)
    at Object.parse (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/acorn/3.2.0/acorn/dist/acorn.js:885:44)
    at Parser.parse (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack/1.13.1/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack/1.13.1/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/enhanced-resolve/0.9.1/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/yeer/go/src/github.com/fundon/vue-admin/node_modules/.npminstall/graceful-fs/4.1.4/graceful-fs/graceful-fs.js:78:16
 @ ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/Components/Progress.vue 11:31-68
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  21.9 kB       0
webpack: bundle is now VALID.

```

**Comment by fundon** [comment]
Try `cnpm rebuild -d`

**Comment by athom** [comment]
work like a charm, thx!

**Comment by leinue** [comment]
i face the same problem,but i have not fixed it
