### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by tudousi991112** [fundon/vue-admin#41]
Listening at http://localhost:8080
/Users/pjj/vue-admin/node_modules/loader-runner/lib/loadLoader.js:35
			throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
			^

Error: Module '/Users/pjj/vue-admin/node_modules/url/url.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/pjj/vue-admin/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/pjj/vue-admin/node_modules/loader-runner/lib/LoaderRunner.js:140:2)
    at runLoaders (/Users/pjj/vue-admin/node_modules/loader-runner/lib/LoaderRunner.js:326:2)
    at NormalModule.doBuild (/Users/pjj/vue-admin/node_modules/webpack/lib/NormalModule.js:125:2)
    at NormalModule.build (/Users/pjj/vue-admin/node_modules/webpack/lib/NormalModule.js:173:15)
    at Compilation.buildModule (/Users/pjj/vue-admin/node_modules/webpack/lib/Compilation.js:127:9)
    at /Users/pjj/vue-admin/node_modules/webpack/lib/Compilation.js:303:10
    at /Users/pjj/vue-admin/node_modules/webpack/lib/NormalModuleFactory.js:63:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/pjj/vue-admin/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/Users/pjj/vue-admin/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/Users/pjj/vue-admin/node_modules/webpack/lib/NormalModuleFactory.js:135:6)
    at /Users/pjj/vue-admin/node_modules/webpack/lib/NormalModuleFactory.js:130:7
    at /Users/pjj/vue-admin/node_modules/async/lib/async.js:726:13
    at /Users/pjj/vue-admin/node_modules/async/lib/async.js:52:16
    at done (/Users/pjj/vue-admin/node_modules/async/lib/async.js:246:17)
    at /Users/pjj/vue-admin/node_modules/async/lib/async.js:44:16

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! vue-admin@0.0.1 dev: `node build/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-admin@0.0.1 dev script 'node build/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pjj/vue-admin/npm-debug.log

**Comment by fundon** [comment]
Thank you! :)
