### ISSUE TITLE
no such file or directory ...

### ISSUE THREAD

**Issue by nevermore22** [fundon/vue-admin#47]
Error: no such file or directory
   at MemoryFileSystem.readFileSync (C:\Users\xhl\node_modules\memory-fs\lib\MemoryFileSystem.js:107:10)
   at devMiddleWare.waitUntilValid (C:\Users\xhl\Desktop\demo-master\vue-admin-next\build\server.js:28:20)
   at Function.webpackDevMiddleware.waitUntilValid (C:\Users\xhl\node_modules\webpack-dev-middleware\middleware.js:228:39)
   at app.get (C:\Users\xhl\Desktop\demo-master\vue-admin-next\build\server.js:26:19)
   at Layer.handle [as handle_request] (C:\Users\xhl\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\xhl\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Users\xhl\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\Users\xhl\node_modules\express\lib\router\layer.js:95:5)
   at C:\Users\xhl\node_modules\express\lib\router\index.js:277:22
   at param (C:\Users\xhl\node_modules\express\lib\router\index.js:349:14)
   at param (C:\Users\xhl\node_modules\express\lib\router\index.js:365:14)
   at Function.process_params (C:\Users\xhl\node_modules\express\lib\router\index.js:410:3)
   at next (C:\Users\xhl\node_modules\express\lib\router\index.js:271:10)
   at middleware (C:\Users\xhl\node_modules\webpack-hot-middleware\middleware.js:39:48)
   at Layer.handle [as handle_request] (C:\Users\xhl\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Users\xhl\node_modules\express\lib\router\index.js:312:13)

node v6.2.0
npm 3.8.9

**Comment by fundon** [comment]
Thank you for your report. 
I'm on macOS, but I will check that.

**Comment by nevermore22** [comment]
额 我是在windows上使用
在build中的server.js中这段好像发生了错误
app.get('*', (req, res) => {
    const fs = devMiddleWare.fileSystem
    devMiddleWare.waitUntilValid(() => { 
        res.end(fs.readFileSync(path.join(config.output.path, '../index.html'))); 
    })
})

**Comment by fundon** [comment]
把 `path.join(config.output.path, '../index.html')` 换成 `path.join(config.output.path, '..', path.sep, 'index.html')` 试试

**Comment by nevermore22** [comment]
ERROR in multi app
Module not found: Error: Cannot resolve 'file' or 'directory' ./client/index.js in c:\Users\xhl\Desktop\demo-master\vue-admin-next\build
 @ multi app
webpack: bundle is now VALID.

这是启动之后 后续还是no such file or directory

**Comment by fundon** [comment]
谢谢反馈，欢迎提交 PR！

**Comment by fundon** [comment]
Related to https://github.com/fundon/vue-admin/issues/39.
