### ISSUE TITLE
Cannot launch npm run dev - object expansion fails in app.js with Unexpected token error

### ISSUE THREAD

**Issue by vek0ng** [fundon/vue-admin#61]
Error when I run npm run dev. Object expansion fails in app.js. It looks like an eslint of babel issue. Any help to fix? In VSCode, same code section in app.js raises an eslint exception: [js] Property exception expected.
<<VSCode>>
const app = new Vue({
  router,
  store,
  nprogress,
  ...App       << eslint error here
})

<<CLI>>
$ npm run dev
...
ERROR in ./client/app.js
Module parse failed: ...\vue-admin\client\app.js Unexpected token (35:2)
You may need an appropriate loader to handle this file type.
|   store,
|   nprogress,
|   ...App
| })
|
 @ ./client/index.js 1:0-27
 @ multi app
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.46 MB       0
webpack: bundle is now VALID.

**Comment by fundon** [comment]
Which is your env?

```console
$ node -v
$ npm -v
$ ./node_modules/.bin/webpack --help | grep webpack
```

**Comment by vek0ng** [comment]
$ node -v
v6.3.0

$ npm -v
3.10.3

$ ./node_modules/.bin/webpack --help | grep webpack
webpack 2.1.0-beta.25
Usage: https://webpack.github.io/docs/cli.html
Usage without config file: webpack <entry> [<entry>] <output>
Usage with config file: webpack

**Comment by fundon** [comment]
Thanks

Below is ES6 syntax, it's ok
```js
| ...App
```

**Comment by fundon** [comment]
Clould you try to execute command `rm -rf node_modules && npm install -d`? Reinstall packages.

`npm run dev` is ok in my local.

**Comment by vek0ng** [comment]
No luck. Same problem.

**Comment by vek0ng** [comment]
Anyone seen this problem? My environment is Cygwin, Windows 10.

**Comment by fundon** [comment]
I'm on macOS.

**Comment by fundon** [comment]
@vek0ng Do you fix this?

**Comment by vek0ng** [comment]
This issue is still not resolved. On Windows 10 Bash:

$ npm run dev

> vue-admin@0.1.0 dev /mnt/c/Dev/Go/src/github.com/vekong/vue-admin
> cross-env NODE_ENV=development node build/dev-server.js

Listening at http://localhost:8080

webpack built d3f68ab3ddb206fe2f81 in 1609ms
Hash: d3f68ab3ddb206fe2f81
Version: webpack 2.1.0-beta.25
Time: 1609ms
    Asset     Size  Chunks       Chunk Names
   app.js  1.62 kB       0       app
vendor.js   705 kB       1       vendor

ERROR in ./build/dev-client.js
Module build failed: Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/babel-loader/index.js:4:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at loadLoader (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/loader-runner/lib/LoaderRunner.js:164:2)
    at runLoaders (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/webpack/lib/NormalModule.js:131:2)
 @ multi app

ERROR in ./client/index.js
Module build failed: Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/babel-loader/index.js:4:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at loadLoader (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/loader-runner/lib/LoaderRunner.js:164:2)
    at runLoaders (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/mnt/c/Dev/Go/src/github.com/vekong/vue-admin/node_modules/webpack/lib/NormalModule.js:131:2)
 @ multi app

**Comment by vek0ng** [comment]
I did a fresh download. It works:

Windows 10 + Cygwin – works ok
Windows 10 + Ubuntu Bash – fails. Known issue [Bash on Ubuntu on Windows, Webpack interface issue #57](https://github.com/SharePoint/sp-dev-docs/issues/57).

> vue-admin@0.1.4 dev /mnt/c/Dev/Go/src/github.com/vekong/vue-admin
> cross-env NODE_ENV=development node build/dev-server.js

Listening at http://localhost:8080

webpack built cbc76e0092e5a7deee14 in 18209ms
Hash: cbc76e0092e5a7deee14
Version: webpack 2.1.0-beta.25
Time: 18209ms
…
ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-1!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./client/App.vue
Module build failed: Error: **EINVAL: invalid argument, uv_interface_addresses**
    at Error (native)
…

Thanks for this great project.

**Comment by fundon** [comment]
@vek0ng Thank you for your share!

Related to https://github.com/Microsoft/BashOnWindows/issues/468.

**Comment by bugs1111** [comment]
@fundon 你好，我也遇到了这个问题，请问最后是怎么解决的？

bash:`npm run dev`

~~~
ERROR in ./client/app.js
Module build failed: SyntaxError: Unexpected token (57:2)

  55 |   store,
  56 |   nprogress,
> 57 |   ...App
     |   ^
  58 | })
  59 |
  60 | export { app, router, store }
~~~

-----
我的开发环境：
- macOS Sierra v10.12.4
- python v2.7
- node v7.9.0
- npm v4.2.0
- webpack v2.4.1
