### ISSUE TITLE
npm hang - npm无法配置开发环境

### ISSUE THREAD

**Issue by edwinyzh** [fundon/vue-admin#63]
您好，似乎您说中文？

我有个问题，不知道能否手工，即不通过npm和web pack来配置开发环境？因为我的npm无法穿墙，如下，停在这里：

```
npm info retry fetch attempt 1 at 22:20:25
npm info attempt registry request try #1 at 22:20:25
npm http fetch GET https://registry.npmjs.org/emojione/-/emojione-2.2.6.tgz
npm http fetch 200 https://registry.npmjs.org/emojione/-/emojione-2.2.6.tgz
[    ..............] - fetchMetadata: http fetch 200 https://registry.npmjs.org

```

我原来主要做桌面开发，刚刚开始接触web开发，请指教。谢谢。

**Comment by edwinyzh** [comment]
说明：今天2016-09-29 刚刚更新了最新版的node.js和npm.

**Comment by motecshine** [comment]
cnpm 使用淘宝的源

**Comment by edwinyzh** [comment]
谢谢！可以了。

**Comment by edwinyzh** [comment]
谢谢！cnpm可以了。
就是无法build 或者`run env`，试了最新的rev，或者release 0.1

```
[1m[31mERROR in ./client/App.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.0.0-rc.7
- vue-template-compiler@2.0.0-rc.8

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.
```

**Comment by fundon** [comment]
`vue` 和 `vue-template-compiler` 需要同一个版本好

1. 更新到最新的源代码

2. 然后 `npm up -d`

**Comment by fundon** [comment]
更新到最新的源代码，并且更新下  npm 。

如果还有问题请重新打开这个 issue，谢谢。

**Comment by edwinyzh** [comment]
执行`npm up `-d成功，但是`npm up -d`问题同样。命令行显示显示 listening on localhost:8080，过了几秒，同样的问题再次发生。

**Comment by fundon** [comment]
更新到最新源码了吗

**Comment by fundon** [comment]
试试`npm install -d`

**Comment by edwinyzh** [comment]
多谢，`npm install -d`执行成功，但是还是同样的问题。。。


```
> vue-admin@0.1.0 dev D:\WebDev\vue-admin-dev
> cross-env NODE_ENV=development node build/dev-server.js

Listening at http://localhost:8080

webpack built 0e0e3bd2832391340850 in 3798ms
Hash: [1m0e0e3bd2832391340850[39m[22m
Version: webpack [1m2.1.0-beta.25[39m[22m
Time: [1m3798[39m[22mms
    [1mAsset[39m[22m    [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m     [1mChunk Names[39m[22m
   [1m[32mapp.js[39m[22m  222 kB       [1m0[39m[22m  [1m[32m[39m[22m     app
[1m[32mvendor.js[39m[22m  959 kB       [1m1[39m[22m  [1m[32m[39m[22m     vendor

[1m[31mERROR in ./client/App.vue
Module build failed: Error: 

Vue packages version mismatch:

- vue@2.0.0-rc.7
- vue-template-compiler@2.0.0-rc.8

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader or vueify, re-installing them should bump vue-template-compiler to the latest.

    at Object.<anonymous> (D:\WebDev\vue-admin-dev\node_modules\.2.0.0-rc.8@vue-template-compiler\index.js:8:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\WebDev\vue-admin-dev\node_modules\.9.5.1@vue-loader\lib\parser.js:1:78)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\WebDev\vue-admin-dev\node_modules\.9.5.1@vue-loader\lib\loader.js:3:13)
    at Module._compile (module.js:409:26)
 @ ./client/app.js 7:0-28
 @ ./client/index.js
 @ multi app[39m[22m

[1m[31mERROR in ./client/views/Home.vue
Module build failed: Error: 

```

**Comment by fundon** [comment]
问题在
```console
- vue@2.0.0-rc.7
- vue-template-compiler@2.0.0-rc.8\
```

请更新到最新源代码
