### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by chslink** [fundon/vue-admin#76]
```powershell
PS C:\Code\JsCode\vue-admin> node -v
v6.9.1
PS C:\Code\JsCode\vue-admin> npm -v
3.10.8
PS C:\Code\JsCode\vue-admin> npm run dev

> vue-admin@0.1.7 dev C:\Code\JsCode\vue-admin
> cross-env NODE_ENV=development node build/dev-server.js

Listening at http://localhost:8080

webpack built ebfb2f8ff48f72ff9a02 in 16017ms
Hash: ebfb2f8ff48f72ff9a02
Version: webpack 2.1.0-beta.25
Time: 16017ms
    Asset     Size        Chunks       Chunk Names
    17.js  46.2 kB            17
     0.js  2.28 MB             0
     2.js  93.4 kB  2, 9, 10, 11
     3.js   213 kB             3
     4.js   125 kB             4
     5.js   164 kB             5
     6.js  96.6 kB             6
     7.js  1.37 MB             7
     8.js   132 kB             8
     9.js  50.3 kB             9
    10.js  45.6 kB            10
    11.js  46.1 kB            11
    12.js  3.46 MB            12
    13.js  11.5 MB            13
    14.js   496 kB            14
    15.js  50.9 kB            15
    16.js  52.3 kB            16
     1.js  2.28 MB             1
    18.js  42.2 kB            18
    19.js  41.7 kB            19
    20.js  52.2 kB            20
    21.js  39.3 kB            21
    22.js    31 kB            22
    23.js  21.7 kB            23
    24.js  40.6 kB            24
    25.js  44.3 kB            25
    26.js  16.8 kB            26
    27.js  33.7 kB            27
    28.js  27.6 kB            28
    29.js  12.4 kB            29
    30.js    14 kB            30
    31.js  6.68 kB            31
    32.js   6.5 kB            32
   app.js   403 kB            33       app
vendor.js   836 kB            34       vendor

ERROR in ./~/.0.25.0@css-loader!./~/.9.7.0@vue-loader/lib/style-rewriter.js?id=data-v-78ad3722!./~/.4.0.2@sass-loader!./
~/.9.7.0@vue-loader/lib/selector.js?type=styles&index=0!./client/App.vue
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Code\JsCode\vue-admin\node_modules\.3.10.1@no
de-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\extensions.js:119:13)
    at foundBinariesList (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\errors.js:45:5)
    at Object.<anonymous> (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\index.js:15:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Code\JsCode\vue-admin\node_modules\.4.0.2@sass-loader\index.js:4:12)
    at Module._compile (module.js:570:32)
 @ ./~/.1.0.0@vue-style-loader!./~/.0.25.0@css-loader!./~/.9.7.0@vue-loader/lib/style-rewriter.js?id=data-v-78ad3722!./~
/.4.0.2@sass-loader!./~/.9.7.0@vue-loader/lib/selector.js?type=styles&index=0!./client/App.vue 4:14-277 13:2-17:4 14:20-
283
 @ ./client/App.vue
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.25.0@css-loader!./~/.9.7.0@vue-loader/lib/style-rewriter.js?id=data-v-0ed41ac8&scoped=true!./~/.4.0.2@sa
ss-loader!./~/.9.7.0@vue-loader/lib/selector.js?type=styles&index=0!./client/views/Home.vue
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Code\JsCode\vue-admin\node_modules\.3.10.1@no
de-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\extensions.js:119:13)
    at foundBinariesList (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\errors.js:45:5)
    at Object.<anonymous> (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\index.js:15:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Code\JsCode\vue-admin\node_modules\.4.0.2@sass-loader\index.js:4:12)
    at Module._compile (module.js:570:32)
 @ ./~/.1.0.0@vue-style-loader!./~/.0.25.0@css-loader!./~/.9.7.0@vue-loader/lib/style-rewriter.js?id=data-v-0ed41ac8&sco
ped=true!./~/.4.0.2@sass-loader!./~/.9.7.0@vue-loader/lib/selector.js?type=styles&index=0!./client/views/Home.vue 4:14-3
02 13:2-17:4 14:20-308
 @ ./client/views/Home.vue
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app

ERROR in ./~/.0.25.0@css-loader!./~/.9.7.0@vue-loader/lib/style-rewriter.js?id=data-v-bf32ac74&scoped=true!./~/.4.0.2@sa
ss-loader!./~/.9.7.0@vue-loader/lib/selector.js?type=styles&index=0!./client/views/components/Collapse.vue
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Code\JsCode\vue-admin\node_modules\.3.10.1@no
de-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\extensions.js:119:13)
    at foundBinariesList (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\errors.js:45:5)
    at Object.<anonymous> (C:\Code\JsCode\vue-admin\node_modules\.3.10.1@node-sass\lib\index.js:15:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Code\JsCode\vue-admin\node_modules\.4.0.2@sass-loader\index.js:4:12)
    at Module._compile (module.js:570:32)
 @ ./~/.1.0.0@vue-style-loader!./~/.0.25.0@css-loader!./~/.9.7.0@vue-loader/lib/style-rewriter.js?id=data-v-bf32ac74&sco
ped=true!./~/.4.0.2@sass-loader!./~/.9.7.0@vue-loader/lib/selector.js?type=styles&index=0!./client/views/components/Coll
apse.vue 4:14-318 13:2-17:4 14:20-324
 @ ./client/views/components/Collapse.vue
 @ ./client/views async ^\.\/.*\.vue$
 @ ./client/router/menu.js
 @ ./client/router/index.js
 @ ./client/app.js
 @ ./client/index.js
 @ multi app
```

**Comment by chslink** [comment]
后面还有大量报错。。
OS：win10 x64
看过那些已经closed的issues，已经执行过 npm up -d了，之前是

**Comment by fundon** [comment]
@chslink `node-sass` 这个模块重新编译下 `npm rebuild node-sass`

**Comment by fundon** [comment]
我先关闭了。如果还有问题请重新打开。
