### ISSUE TITLE
Module build failed: Error: No ESLint configuration found.

### ISSUE THREAD

**Issue by TomasPangzi** [fundon/vue-admin#79]
ERROR in ./build/dev-client.js
Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint/lib/config.js:256:22)
    at processText (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint/lib/cli-engine.js:756:26)
    at lint (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint-loader/index.js:42:18)
    at Object.module.exports (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint-loader/index.js:178:3)
 @ multi app

ERROR in ./client/index.js
Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint/lib/config.js:256:22)
    at processText (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint/lib/cli-engine.js:756:26)
    at lint (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint-loader/index.js:42:18)
    at Object.module.exports (/Users/bin/Documents/Tomas/Code/Mask/Web/node_modules/eslint-loader/index.js:178:3)
 @ multi app

npm -v 3.10.8,
node -v v6.9.1

**Comment by fundon** [comment]
A `.eslintrc` file is required!

**Comment by TomasPangzi** [comment]
@fundon  Where can I get this file?

**Comment by fundon** [comment]
Here https://github.com/fundon/vue-admin/blob/master/.eslintrc.js

**Comment by TomasPangzi** [comment]
thx @fundon  I will try it

**Comment by arekgofi** [comment]
For me excluding node_modules resolved the issue:
`    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: "eslint-loader",
        options: {
          // eslint options (if necessary)
        }
      },
    ],`

**Comment by piyushSinghalDemo** [comment]
eslintrc.js file is available still getting the same issue, is there any other way?

**Comment by onekiloparsec** [comment]
@piyushSinghalDemo make sure your filename start with a dot: `.eslintrc.js`
